language: c

sudo: false

env:
  global:
    - VERSION=1.1-0
    - NAME=lua-resty-openidc
    - ROCKSPEC=$NAME-$VERSION.rockspec
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install Lua-cURL --server=https://luarocks.org/dev
  - luarocks install lunitx

install:
  - luarocks make $ROCKSPEC CFLAGS="-O2 -fPIC -fprofile-arcs" LIBFLAG="-shared"

script:
  - luarocks pack $ROCKSPEC
  - luarocks upload $ROCKSPEC --api-key=$API_KEY # The API key comes from an environment variable configured on https://travis-ci.org/

notifications:
  email:
    on_success: change
    on_failure: always